FROM node:9-alpine


WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install

#RECUERDA CAMBIAR A INDEX CUANDO FUNCIONE
COPY server.js .
COPY db.js .
COPY bills.js .

EXPOSE 3000

CMD npm start