FROM node:9-alpine


WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY index.js .
COPY db.js .
COPY bills.js .
COPY server.js .
COPY billsResource.js .
 
EXPOSE 5002

CMD npm start